# Generated by Django 5.2.4 on 2025-07-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_weeklyplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
    ]
